version: "3.6"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
services:
  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter
    ports:
      - "8889:8888"
      - "4040:4040"
    volumes:
      - shared-workspace:/opt/workspace
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
  spark-master:
    image: spark-master:1.0.0
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - shared-workspace:/opt/workspace
  spark-worker-1:
    image: spark-worker:1.0.0
    container_name: spark-worker
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - "8081:8081"
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master